### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [eybmv/franklin-w-dixon_the-house-on-the-cliff#1]
# General Issues:

- [ ] Re-run `se clean .` and commit the changes.

- [ ] Re-run `se modernize-spelling .` and commit most of the changes. Don't keep the change in:
`<p>“The Polucca place!” exclaimed the chief, pursing his lips. “We-ll, you see, it ain’t in the city limits.”</p>`

- [ ] Re-run `se interactive-replace "\b([Ss])ome one" "\1omeone" src/epub/text/*` and accept the change.

- [ ] Re-run `se interactive-replace "\b([Aa])ny one" "\1nyone" src/epub/text/*` and accept the changes.

- [ ] Re-run `se build-images .` and commit the changes.

# chapter-13.xhtml:

- [ ] In `“We-ll, you see, it ain’t in the city limits.”`, convert the hyphen into a non-break hyphen ([SEMOS 8.7.7.6](https://standardebooks.org/manual/1.7.3/single-page#8.7.7.6)).

# chapter-14.xhtml:

- [ ] Remove italics from `Napoli` ([SEMOS 8.2.9.2](https://standardebooks.org/manual/1.7.3/single-page#8.2.9.2)).

# content.opf:

- [ ] There are some typos in your descriptions.

- [ ] The short description should not include proper names ([SEMOS 9.6.1.2](https://standardebooks.org/manual/1.7.3/single-page#9.6.1.2)).
